# Generated by Django 5.0.4 on 2024-06-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_tweet_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='like',
            new_name='likes',
        ),
    ]
